### ISSUE TITLE
 "Property 'render' does not exist on type '{}'"

### ISSUE THREAD

**Issue by devYusuf** [denjucks/denjucks#3] opened 2020-05-19 09:26 UTC
I tried out denjucks after seeing that all deno template engine dont work well and I'm getting the errors
![Selection_006](https://user-images.githubusercontent.com/48928718/82309585-39731980-99bb-11ea-8e3a-9e5bcb1dbad4.png)
![Selection_007](https://user-images.githubusercontent.com/48928718/82309617-40019100-99bb-11ea-9bcd-34f6ed0ea297.png)

**Comment by khrome83** [comment] 2020-05-19 14:09
I am seeing the same issue with renderString() as well.

The denjucks import seems to fail.

**Comment by khrome83** [comment] 2020-05-19 14:16
Is this a typing error? I can console.log() the output, but when used in a `.ts` file, deno bundle will fail. Seems like it's a type issue where typescript seems to think render and renderString does not exist?

**Comment by khrome83** [comment] 2020-05-19 15:44
Work Around. @devYusuf you would replace `renderString` with `render`

```
interface Denjucks {
  renderString: Function;
}

import {
  createNowFn,
  NowRequest,
  NowResponse,
} from "https://denopkg.com/grikomsn/deno-create-now-fn/mod.ts";
import denjucks from "https://deno.land/x/denjucks/mod.js";

export const handler = createNowFn(
  async (req: NowRequest, res: NowResponse) => {
    const x = (denjucks as Denjucks).renderString("hello {{ txt }}", {
      txt: "world",
    });
    res.send(x);
  }
);
```

@denjucks - are we able to convert this to TS, or get Type Definitions. Right now because of how Deno works, this is unusable out of the box with Deno and TS.

**Comment by denjucks** [comment] 2020-05-20 05:00
Thanks for alerting me to this. I am not able to replicate this issue unfortunately, so am having some trouble figuring out what needs to be updated in the code. I was able to compile and run typescript files using denjucks, and was able to bundle denjucks using deno bundle and everything seems to work on my end. Do you have the output from the compilation where it is failing? Also, what platform are you on?

**Comment by khrome83** [comment] 2020-05-20 12:01
I am using deno 1.0.
Mac OS 10.15.4

```bash
deno bundle index.ts
```
```bash
Bundling file:///index.ts
error: Uncaught AssertionError: Assertion failed.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1355:5)
    at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:74:9)
```

I don't get the issue on run, just bundle.

VS Code reports also that there are no types. I am using the DENO plugin for VS Code.

**Comment by denjucks** [comment] 2020-05-20 21:02
Trying to get a handle on this, but still can reproduce the error. I am doing the following steps based on the examples in the repo:

1) Running `deno bundle https://deno.land/x/denjucks/mod.js denjucks.ts`
2) Creating a file called `index.ts` with the following code:

```
import denjucks from "./denjucks.ts";

console.log(
    denjucks.renderString("hello {{ txt }}", {txt: "world"})
);
```

3) Running `deno bundle index.ts bundle.ts`
4) Running `deno run --allow-read bundle.ts`

And it returns the expected output from the example (`hello world` in this case). I am on Linux and not using the VS code plugin, doing the bundling and running at the command line. Will this give you an error when trying to bundle?

**Comment by khrome83** [comment] 2020-05-20 22:27
Try not bundling first. Curious if that is the difference.

**Comment by denjucks** [comment] 2020-05-20 23:01
You're right, if I bundle together it fails with the same error, but when I bundle denjucks first, link it to the bundled denjucks file, and then bundle as above it works. Not sure why it fails to bundle when importing from the URL though.

**Comment by khrome83** [comment] 2020-05-24 16:18
Have you made any progress on figuring this out? I am stumped as well and not sure how to proceed. 

If I am not mistaken, I should be using the non bundled version so the final output does tree shaking and optimizations right.

**Comment by denjucks** [comment] 2020-05-27 21:45
I added a type declaration file to the repo from definitely typed, and made an update to the repo to fix a big. Can you try bundling again? I bundled the following file, and it created a single working bundle without having to bundle denjucks first:

`index.js`
```javascript
import denjucks from "https://deno.land/x/denjucks/mod.js";

console.log(denjucks.renderString("{{hello}}", {"hello": "world"}));
```

and then bundled with `deno bundle index.js bundle.js`

**Comment by denjucks** [comment] 2020-06-03 20:43
Gonna close this for now. Let me know if its still an issue, and I can reopen

**Closed by denjucks** 2020-06-03 20:43 UTC
